# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    exclude:
      - "*"
  paths:
    exclude:
      - README.md # Assuming README.md is not modified frequently

pr:
  branches:
    include:
      - "*"

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      echo "Checking terraform"
      terraform -version

    displayName: "Checking for installed terraform version"

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo "Installing Terraform"
      wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      sudo apt update && sudo apt install terraform

      terraform -version

    displayName: "Installing terraform"

  - script: |
      echo "Applying Terraform"
      cd Azure
      terraform init
      terraform plan

    displayName: "Initializing terraform"
